create table Person
(
    id         int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(255) NOT NULL,
    surname    varchar(255) NOT NULL,
    patronymic varchar(255) NOT NULL,
    birth_year int          NOT NULL check (birth_year > 1900 and birth_year < 2026),
    CONSTRAINT unique_person UNIQUE (name, surname, patronymic)
);

create table Book
(
    book_id       int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id       int          references Person (id) ON DELETE SET NULL,
    name          varchar(255) NOT NULL,
    author_name   varchar(255) NOT NULL,
    creating_year int          NOT NULL check (creating_year > 1900 and creating_year < 2026)
);